### ISSUE TITLE
Hashing algorith change for digital signature

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#1]
Change back to using the Message Digest algorithm SHA-256 instead of using MAC HmacSHA256, the use of HMAC's secret key is of no use in the way we are doing digital signatures.

Ex:
`MessageDigest md = MessageDigest.getInstance("SHA-256");`

**Comment by cawwot** [comment]
*ex: 
messageDigest md = new messageDigest;
md.getInstance("SHA-256");

**Comment by shadowx787** [comment]
Edited hashTimesheet function and verified it's working correctly wit the new changes.

**Comment by shadowx787** [comment]
http://www.xorbin.com/tools/sha256-hash-calculator

Get source to check that hash being generated is correct.

Add print statement that uses the bytesToHex function to see the String for the hash.
