### ISSUE TITLE
Should public keys be stored in the database?

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#10]
In order to verify a digital signature the user verifying needs to have access to the users timesheet and to the users public key.  The two options I can think of are either storing the public keys in the database or having another keystore that has all users public keys.  Not really sure if one is better than the other, but I think storing the public keys in the database would be easiest.

Maybe the public key could be stored in the Employee table?  I believe the datatype is going to be varbinary(294).

**Comment by wvelebanks** [comment]
Justin, it seems like the second option is viable. I can add the column to the employee table then,
varbinary(294) ? I'll add it then.

**Comment by cawwot** [comment]
public key can be stored in employee table. Closing ticket
