### ISSUE TITLE
Hash ETMS user passwords

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#16]
The passwords stored in the ETMS user database should be stored as hashes not in plaintext.  The same for user passwords that are sent from the ETMS client.  This way no user passwords are ever sent in plaintext or stored in plaintext.

Since we are already using SHA 256 hasing for other parts of the program it makes sense to continue using it here.  So for the DB that means changing the password field type to CHAR(64) to be able to store the password hash in HEX.  We already have a method to create SHA 256 hash from a string so we just need to call that along with the bytesToHex function to convert it from binary to a HEX String to send to the DB.

**Comment by shadowx787** [comment]
I've updated the code to take the password the user enters and hash it using the SHA 256 hashing algorithm and then convert it to a String to send to the DB for credential matching.  Whenever we create a new user in the DB from now on we'll have to make sure the password is created using the following function:

`SHA2('somepassword',256)`

**Comment by wvelebanks** [comment]
DB has been updated also to the data type required for  this function to work.
