### ISSUE TITLE
Create a Timesheet Object Class

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#17]
A Object class needs to be created for a Timesheet.  This object should contain all the values stored in the ETMS database for the Timesheet table.  We can then use this object to load information from the object into the Web GUI, and write data from the web GUI back into the object which can then be sent back to the Database as an update statement.

So we can pass this Timesheet object to other functions such as:
loadTimesheet - which will load the timesheet into the Web GUI
saveTimesheet - which will save the timesheet info from the Web GUI into the object

verifyTimesheet - will check the data provided in the Web GUI is valid before saveTimesheet is allowed to run.

Right now I'm just thinking some basic get and set methods for all the data stored in the object?

**Comment by shadowx787** [comment]
Looking at how the DB is structured it looks like you'll need to grab everything for a particular payperiod, which the more I look at it I'm not sure I like the DB structure but it's probably a little too late to change that now.

**Comment by wvelebanks** [comment]
actually there should be a couple of objects instead of just one. (it will make it much more complex than it should be that way). The structure of the DB is fine as long as we fit the objects to it.

**Comment by cawwot** [comment]
Committed Timesheet.java, three constructors are included; no arg, basic timesheet params, and full timesheet
