### ISSUE TITLE
MySQL client software credentials

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#2]
Figure out how we will store the password for the etms client software to connect to the MySQL server.  I’m thinking in the my.ini file but we must then create a service account on the system (a windows or UNIX account)  that can only execute the MySQL service, access the my.ini file, and etms.cfg file .  The my.ini file should not be able to be read or written to by a user since it will contain credentials that grant administrative privileges to the EMTS database.

The deliverable would be documentation specifying why and how to setup this etms service account.

Other suggestions to handle this issue are still open.

**Comment by cawwot** [comment]
Can we assume that the MySQL service is already running? If so, the question is how to store the password in a whitebox-secure way. Perhaps the cfg file could be used?

**Comment by shadowx787** [comment]
Yes I agree, I think we can use the cfg file to store the credentials as well.  For some reason I was thinking the my.ini file was still used by the client but it's not at all only the settings we set in the java connection are used.  So I am going to close this ticket and just add the client credentials to the other ticket for the etms.cfg file.  We will just have to make sure that file is restricted from user access some how.
