### ISSUE TITLE
ETMS Configuration File

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#3]
We will need to create a etms configuration file (etms.cfg?)  that is only editable/viewable by an admin or the etms service account on the system.  This configuration file will contain:

- client username

- client password

- server hostname/ip address

- path to the keystore 

- keystore password

- path to the truststore

- truststore password

These configurations are critical in setting up the client connection to the database, that means this configuration file needs to be read-in before the client software is able to connect to the database server.

Currently these values are hard coded for testing purposes.

**Comment by shadowx787** [comment]
Created a file that must be named "etms.cfg" and located within the same directory as the etms software.
Example of current valid fields that are read in are:

- client_username=etms-client

- client_password=my@w3someP@$$w0rd

- server_address=localhost

- keystore_path=C:/Users/Test/Desktop/mysql/test_certs_keys/client.keystore

- keystore_password=somepassword

- truststore_path=C:/Users/Test/Desktop/mysql/test_certs_keys/truststore

- truststore_password=someotherpassword

Ordering of the different settings does not matter.  Still need to figure out a way to secure this file so users can not read or edit it. Also maybe this file should be auto-generated if for some reason it doesn't exist?

**Comment by shadowx787** [comment]
I am going to close this ticket out and create another ticket specifically for figuring out how to secure this file and possibly to auto generate it if it doesn't exist.  What do you guys think?

**Comment by cawwot** [comment]
Can't be auto generated, should be placed by an installer (or in our case an "installation service"). Will require some sort of security, but maybe we can call that out of scope? Ticket can be closed.

**Comment by shadowx787** [comment]
Hmmm I will create a new ticket just to think about securing this file, but your right we could leave it up to the admin to put the right restrictions on the file.  But it is a kind of big deal if the admin forgets because it has the credentials necessary to access everything in the DB.
