### ISSUE TITLE
Create ETMS Database Schema

### ISSUE THREAD

**Issue by shadowx787** [wvelebanks/CMSC495#4]
Follow the documentation the team has created and shared on Google Sheets for the tables, fields, and Char types to create the ETMS database in MySQL.  Once the database schema has been created it should be shared on github so we can start testing our current code with it.

**Comment by wvelebanks** [comment]
Still confused with this section if I have to re-create the entire db here, Again.

**Comment by wvelebanks** [comment]
All Tables belonging to the ETMS Schema are under the ETMSDB folder.
